config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :boards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :mines, dependent: :destroy
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
  validates :name, presence: true, length: { maximum: 50 }
  validates :height, presence: true, :numericality => { greater_than_or_equal_to: 0 }
  validates :width, presence: true, :numericality => { greater_than_or_equal_to: 0 }
  validates :no_mines, presence: true, :numericality => { greater_than_or_equal_to: 0 }
  validates_numericality_of :no_mines, :less_than => Proc.new { |minesweeper_board| minesweeper_board.width * minesweeper_board.height + 1 }


  def to_matrix
    matrix = Array.new(self.height) { Array.new(self.width) {nil} }
    mines = self.mines
    mines.each do |mine|
      matrix[mine.y][mine.x] = :mine
    end
    matrix
  end

  def generate
    return false if self.no_mines > self.height * self.width
    matrix = Array.new(self.height) { Array.new(self.width) {nil} }
    mines = []
    height_mine = *(0..self.height - 1)
    width_mine = *(0..self.width - 1)
    mines_location = height_mine.product(width_mine)
    mines_location.shuffle!
    (0..self.no_mines - 1).each do |i|
      x_pos = mines_location[i][0]
      y_pos = mines_location[i][1]
      matrix[y_pos][x_pos] = :mine
      mine = { x: x_pos, y: y_pos, created_at: Time.now, updated_at: Time.now }
      mines << mine
    end
    Board.transaction do
      self.save!
      Mine.insert_all(mines.map{ |mine| mine[:board_id] = self.id; mine }) if mines.any?
    end
    matrix
  end

end

app/models/mine.rb
class Mine < ApplicationRecord
  belongs_to :board
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    if params[:all].present? && params[:all] == "true"
      @boards = Board.all
    else
      @boards = Board.last(10).reverse
    end
  end

  def show
    @board = Board.find(params[:id])
  end

  def create
    @board = Board.new(board_params)
    if @board.generate
      redirect_to boards_path
    else
      render 'static_pages/home'
    end
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
  end

  private
  def board_params
    params.require(:board).permit(:email, :width, :height, :no_mines, :name)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @board = Board.new
    @boards = Board.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/destroy.js.erb
document.querySelector('#board-<%= @board.id%>').remove()

app/views/boards/index.html.haml
%div.mt-10.ml-10
  =link_to 'Back', root_path
.container.mt-8.px-5
  %table.table
    %thead.thead-dark
      %th{:scope => "col"}= "Name"
      %th{:scope => "col"}= "Email"
      %th{:scope => "col"}= "Width"
      %th{:scope => "col"}= "Height"
      %th{:scope => "col"}= "Mines"
      %th{:scope => "col"}= "Created at"
      %th{:scope => "col"}= "Delete Board"
    - @boards.each do |board|
      %tbody{:id => "board-#{board.id}"}
        %tr
          %td= link_to board.name, board
          %td= board.email
          %td= board.width
          %td= board.height
          %td= board.no_mines
          %td= board.created_at.to_time.strftime('%B %e at %l:%M %p')
          %td.text-center
            =link_to 'Delete', board_path(board), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

  - if Board.all.length > 10
    .text-center.mb-20
      - if params[:all].present? && params[:all] == "true"
        = link_to 'View last 10 generated boards', boards_path(:all => false), :class => 'btn btn-primary'
      - else
        = link_to 'View all generated boards', boards_path(:all => true), :class => 'btn btn-primary'

app/views/boards/show.html.haml
%div.mt-10.ml-10
  =link_to 'Back', boards_path
%div.mt-10.flex.flex-col.items-center
  %h1
    Name: #{@board.name}
  %h2
    Email: #{@board.email}

  %h1.mt-10
    - matrix = @board.to_matrix
    - (0..@board.width-1).each do |row|
      - (0..@board.height-1).each do |col|
        - if matrix[row][col] == nil
          = "🌫"
        - else
          = "💣"
      %br

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minesweeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |message|
        .text-base.font-normal.pt-2.pb-6.absolute.left-0.right-0.top-4
          .bg-red-500.p-3.rounded.flex.items-start.text-white.my-4.shadow-lg.mx-auto.max-w-lg.text-left.alert
            .text-lg.my-auto
              %i.fas.fa-exclamation-circle
            .px-3.my-auto.flex-grow= content_tag(:div, message)
            .text-lg.my-auto.transform.transition.cursor-pointer.hover:scale-110.duration-300.ease-in-out.close
              %i.fas.fa-times

app/views/static_pages/home.html.haml
.container.mt-28.px-5.flex
  %div.m-auto.mx-auto
    %h1
      Welcome to Minesweeper
    .mx-auto
      = form_for :board, url: boards_path, method: :post do |f|
        .flex.flex-column.gap-4.mt-5
          = f.email_field :email, placeholder: 'Email', class: 'rounded-lg'
          = f.number_field :width, placeholder: 'Width', class: 'rounded-lg'
          = f.number_field :height, placeholder: 'Height', class: 'rounded-lg'
          = f.number_field :no_mines, placeholder: 'Number of Mines', class: 'rounded-lg'
          = f.text_field :name, placeholder: 'Board Name', class: 'rounded-lg'
          = f.submit 'Generate Board', class: 'submit-btn w-2/3 mx-auto btn btn-primary rounded-lg'
    = link_to "See generated boards", boards_path